name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to SmartNotes! 📝 If you have any questions, feedback, or ideas, feel free to create an issue. We're here to help and improve together!"
        pr-message: "Congratulations on your first pull request for SmartNotes! 🚀 Your contribution is valuable. It will be reviewed shortly. Thanks for making SmartNotes even better!"
